### Entity 를 통한 POST Mapping
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "name": "hello4"
}

### DTO를 통한 POST Mapping
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
  "name": "hello3"
}

### DTO를 통한 PATCH
PATCH http://localhost:8080/api/v2/members/1
Content-Type: application/json

{
  "name": "patchName"
}

### Member Entity 로 전체 조회
GET http://localhost:8080/api/v1/members

### Member DTO 로 전체 조회
GET http://localhost:8080/api/v2/members