### Entity 직접 노출
GET http://localhost:8080/api/v1/orders

### DTO 노출
GET http://localhost:8080/api/v2/orders

### Fetch Join 으로 성능 최적화
GET http://localhost:8080/api/v3/orders

### Fetch Join + Batch Size 를 이용한 페이징 조회
GET http://localhost:8080/api/v3.1/orders?offset=0&limit=100

### JPA 에서 DTO 직접 조회
GET http://localhost:8080/api/v4/orders

### JPA 에서 DTO 직접 조회 - 최적화
GET http://localhost:8080/api/v5/orders

### JPA 에서 DTO 직접 조회 - 플랫 데이터 최적화
GET http://localhost:8080/api/v6/orders